# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9966dc648683377b495dc8e5b5a704b1"
name = "xapps-geo-ts"
handle = "xapps-geo-ts"
application_url = "https://employed-travis-elite-chaos.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "appstorefortests.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_files,read_locales,read_markets,read_themes,write_files"

[auth]
redirect_urls = [
  "https://employed-travis-elite-chaos.trycloudflare.com/auth/callback",
  "https://employed-travis-elite-chaos.trycloudflare.com/auth/shopify/callback",
  "https://employed-travis-elite-chaos.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-10"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://flip-symphony-happiness-actress.trycloudflare.com/gdpr-customers-redact"
  customer_data_request_url = "https://flip-symphony-happiness-actress.trycloudflare.com/gdpr-customers-data-request"
  shop_deletion_url = "https://flip-symphony-happiness-actress.trycloudflare.com/gdpr-shop-redact"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update", "app/uninstalled" ]
  uri = "/api/webhooks"

[pos]
embedded = false
